from django.forms import ModelForm
from django import forms
from .models import Project


class ProjectForm(ModelForm):  # Django creates a form based on Project module
    class Meta:
        # Django is gonna ahead and generate a field of each available attribute,
        # except id and created attributes that are automatically generated by db and arent modifiable
        model = Project

        # Create automatically generated form by attributes in db
        fields = ['title', 'description', 'featured_image', 'demo_link', 'source_link', 'tags']

        # Add attributes to specific/each field
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

        # Below second option to write instead of above for loop
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': 'Add title'})
        #
        # self.fields['description'].widget.attrs.update({'class': 'input', 'placeholder': 'Add title'}) etc...