from django.forms import ModelForm
from .models import Project


class ProjectForm(ModelForm):  # Django creates a form based on Project module
    class Meta:
        # Django is gonna ahead and generate a field of each available attribute,
        # except id and created attributes that are automatically generated by db and arent modifiable
        model = Project

        # Create automatically generated form by attributes in db
        fields = ['title', 'description', 'featured_image', 'demo_link', 'source_link', 'tags']
